- id: "1717915948870"
  alias: DailyBackupSynology
  description: Tägliches Backup auf Synology
  trigger:
    - platform: time
      at: "10:00:00"
  condition: []
  action:
    - service: hassio.backup_full
      metadata: {}
      data:
        compressed: true
        homeassistant_exclude_database: false
        location: Synology_backup
  mode: single
