# Loads default set of integrations. Do not remove.
default_config:


# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

  
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


# -----------------------SYSTEM------------------------------
time_date:
  display_options:
    - "time"
# --------------------INTEGRATION----------------------------
# -----------------------------------------------------------
sensor:
  - platform: integration
    source: sensor.solarnet_pv_leistung
    name: energy_pv
    unit_prefix: k
    round: 2

mqtt:
  - binary_sensor:
      name: "dev05_motion"
      state_topic: "std/dev05/s/pir/status"
      device_class: motion
  - binary_sensor:
      name: "dev62_motion"
      state_topic: "std/dev62/s/pir/status"
      device_class: motion
  - binary_sensor:
      name: "dev63_motion"
      state_topic: "std/dev63/s/pir/status"
      device_class: motion
  - binary_sensor:
      name: "dev71_motion"
      state_topic: "std/dev71/s/pir/status"
      device_class: motion
  - binary_sensor:
      name: "dev301_garb_rest"
      state_topic: "std/dev301/s/garbage/rest"
  - binary_sensor:
      name: "dev301_garb_paper"
      state_topic: "std/dev301/s/garbage/paper"
  - binary_sensor:
      name: "dev301_garb_plastic"
      state_topic: "std/dev301/s/garbage/plastic"
  - binary_sensor:
      name: "dev301_garb_organic"
      state_topic: "std/dev301/s/garbage/organic"
  # --------------------------------------------------
  - light:
      name: "dev01"
      state_topic: "std/dev01/s/so_basic/status"
      command_topic: "std/dev01/r/so_basic/switch"
      qos: 0
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
  - light:
      name: "dev04"
      state_topic: "std/dev04/s/so_basic/status"
      command_topic: "std/dev04/r/so_basic/switch"
      qos: 0
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
  - light:
      name: "dev05"
      state_topic: "std/dev05/s/so_basic/status"
      command_topic: "std/dev05/r/so_basic/switch"
      qos: 0
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
  - light:
      name: "dev50_r1"
      state_topic: "std/dev50/s/relay_one/status"
      command_topic: "std/dev50/r/relay_one/switch"
      qos: 0
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
  - light:
      name: "dev50_r2"
      state_topic: "std/dev50/s/relay_two/status"
      command_topic: "std/dev50/r/relay_two/switch"
      qos: 0
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
  - light:
      name: "dev50_r3"
      state_topic: "std/dev50/s/relay_three/status"
      command_topic: "std/dev50/r/relay_three/switch"
      qos: 0
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
  - light:
      name: "dev50_r4"
      state_topic: "std/dev50/s/relay_four/status"
      command_topic: "std/dev50/r/relay_four/switch"
      qos: 0
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
  - light:
      name: "dev50_r5"
      state_topic: "std/dev50/s/relay_five/status"
      command_topic: "std/dev50/r/relay_five/switch"
      qos: 0
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
  - light:
      name: "dev50_r6"
      state_topic: "std/dev50/s/relay_six/status"
      command_topic: "std/dev50/r/relay_six/switch"
      qos: 0
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
  - light:
      name: "dev50_r7"
      state_topic: "std/dev50/s/relay_seven/status"
      command_topic: "std/dev50/r/relay_seven/switch"
      qos: 0
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
  - light: ### garden control station 50
      name: "dev50_r8"
      state_topic: "std/dev50/s/relay_eight/status"
      command_topic: "std/dev50/r/relay_eight/switch"
      qos: 0
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
  - light: ### light 62 carport outside
      name: "dev62"
      state_topic: "std/dev62/s/so_basic/status"
      command_topic: "std/dev62/r/so_basic/switch"
      qos: 0
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
  - light: ### garden house
      name: "dev63"
      state_topic: "std/dev63/s/so_basic/status"
      command_topic: "std/dev63/r/so_basic/switch"
      qos: 0
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
  - light: ### flur
      name: "dev70"
      state_topic: "std/dev70/s/light_one/status"
      command_topic: "std/dev70/r/light_one/switch"
      rgb_state_topic: "std/dev70/s/light_one/color"
      rgb_command_topic: "std/dev70/r/light_one/color"
      brightness_state_topic: "std/dev70/s/light_one/brightness"
      brightness_command_topic: "std/dev70/r/light_one/brightness"
      retain: True
      qos: 0
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
      brightness_scale: 99
  - light: ### Carport work room
      name: "dev71"
      state_topic: "std/dev71/s/light_one/status"
      command_topic: "std/dev71/r/light_one/switch"
      rgb_state_topic: "std/dev71/s/light_one/color"
      rgb_command_topic: "std/dev71/r/light_one/color"
      brightness_state_topic: "std/dev71/s/light_one/brightness"
      brightness_command_topic: "std/dev71/r/light_one/brightness"
      retain: True
      qos: 0
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
      brightness_scale: 99
  - light: ### H801 LED ctrl channel 1: furniture living room
      name: "dev80_l1"
      state_topic: "std/dev80/s/light_one/status"
      command_topic: "std/dev80/r/light_one/switch"
      brightness_state_topic: "std/dev80/s/light_one/brightness"
      brightness_command_topic: "std/dev80/r/light_one/brightness"
      retain: True
      qos: 0
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
      brightness_scale: 99
  - light: ### H801 LED ctrl channel 2: furniture living room
      name: "dev80_l2"
      state_topic: "std/dev80/s/light_two/status"
      command_topic: "std/dev80/r/light_two/switch"
      brightness_state_topic: "std/dev80/s/light_two/brightness"
      brightness_command_topic: "std/dev80/r/light_two/brightness"
      retain: True
      qos: 0
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
      brightness_scale: 99
  - light: ### H801 LED ctrl channel 3: furniture living room
      name: "dev80_l3"
      state_topic: "std/dev80/s/light_three/status"
      command_topic: "std/dev80/r/light_three/switch"
      brightness_state_topic: "std/dev80/s/light_three/brightness"
      brightness_command_topic: "std/dev80/r/light_three/brightness"
      retain: True
      qos: 0
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
      brightness_scale: 99
  #--------------------------------------
  - switch:
      state_topic: "std/dev102/s/0/switch"
      command_topic: "std/dev102/s/0/switch/cmd"
      name: "dev102_switch"
  - switch:
      state_topic: "std/dev101/s/0/switch"
      command_topic: "std/dev101/s/0/switch/cmd"
      name: "dev101_switch"

  # --------------- MQTT --------------------------------------
  # ------------------DEV 24-----------------------------------
  - sensor:
      state_topic: "dev24/#"
      name: "dev24"
  - sensor:
      state_topic: "std/dev24/s/temp_hum/temp"
      name: "dev24_temperature_dht"
      unit_of_measurement: "ºC"

  - sensor:
      state_topic: "std/dev24/s/temp_hum/hum"
      name: "dev24_humidity_dht"
      unit_of_measurement: "%"
  # ------------------DEV 28-----------------------------------
  - sensor:
      state_topic: "dev28/#"
      name: "dev28"
  - sensor:
      state_topic: "std/dev28/s/temp_hum/temp"
      name: "dev28_temperature_dht"
      unit_of_measurement: "ºC"
  - sensor:
      state_topic: "std/dev28/s/temp_hum/hum"
      name: "dev28_humidity_dht"
      unit_of_measurement: "%"
  - sensor:
      state_topic: "std/dev28/s/temp_hum/temp1"
      name: "dev28_temperature_dht1"
      unit_of_measurement: "ºC"
  - sensor:
      state_topic: "std/dev28/s/temp_hum/hum1"
      name: "dev28_humidity_dht1"
      unit_of_measurement: "%"
  # -----------------------------------------------------------
  - sensor:
      state_topic: "dev71/#"
      name: "dev71"
  - sensor:
      state_topic: "std/dev71/s/temp_hum/temp"
      name: "dev71_temperature_dht"
      unit_of_measurement: "ºC"
  - sensor:
      state_topic: "std/dev71/s/temp_hum/hum"
      name: "dev71_humidity_dht"
      unit_of_measurement: "%"
  - sensor:
      state_topic: "std/dev71/s/temt6000/raw"
      name: "dev71_brightness_temt6000"
      unit_of_measurement: "raw"
  - sensor:
      state_topic: "std/dev71/s/health/tic"
      name: "dev71_health_tic"
      unit_of_measurement: "cnt"
  # -----------------------------------------------------------
  - sensor:
      state_topic: "dev300/#"
      name: "dev300"
  - sensor:
      state_topic: "std/dev300/s/hb/heart_beat"
      name: "dev300_heart_beat"
      unit_of_measurement: "cnt"
  - sensor:
      state_topic: "std/dev300/s/hb/time_now"
      name: "dev300_time_now"
  - sensor:
      state_topic: "std/dev300/s/hb/ts_now"
      name: "dev300_ts_now"
  # -----------------------------------------------------------
  - sensor:
      state_topic: "dev301/#"
      name: "dev301"
  - sensor:
      state_topic: "std/dev301/s/ener_wat/gas"
      name: "dev301_gas"
      unit_of_measurement: "qm"
  - sensor:
      state_topic: "std/dev301/s/ener_wat/power"
      name: "dev301_power"
      unit_of_measurement: "kWh"
  - sensor:
      state_topic: "std/dev301/s/ener_wat/water"
      name: "dev301_water"
      unit_of_measurement: "qm"
  - sensor:
      state_topic: "std/dev301/s/ener_wat/date"
      name: "dev301_date"
